### PR TITLE
Update cs:group formatting attribute treatment

### PR DESCRIPTION
**Pull request by inukshuk**
See the discussion at: http://xbiblio-devel.2463403.n2.nabble.com/Group-formatting-td7578925.html

### CODE REVIEW

**Comment by bdarcus** [comment]
Bumping.

Obviously if we merge, the merge conflict would need to be resolved. I think a `get merge master` will fix it, as it's probably just because I changed the file extension.

**Comment by bdarcus** [comment]
Anyone want to propose resolution to this and the related linked issue?

**Comment by fbennett** [comment]
My views and the reasoning behind them are set down in https://github.com/citation-style-language/documentation/issues/65:
* ``cs:choose`` itself should not be treated as a "rendering element;" and
* formatting attributes on ``cs:group`` should be applied to the group as a whole, and not "transmitted" to its children.

Styles in the CSL repository are based on these assumptions.

**Comment by bwiernik** [comment]
See the PR here: https://github.com/citation-style-language/documentation/pull/116

**Pull request merged**
