### PR TITLE
Change description of `annote`

### PR DESCRIPTION
**Pull request by denismaier**
Fixes https://github.com/citation-style-language/csl-evolution/issues/28

### CODE REVIEW

**Comment by adam3smith** [comment]
Should we explicitly mention annotated bibliography? Are there other use cases? Definitely approve of the direction of this change, but I think we can make this even clearer

**Comment by denismaier** [comment]
Something like this?

"annotations on the bibliography entry (e.g. for annotated bibliographies or to give additional bibliographic information about an entry)"

**Comment by rmzelle** [comment]
First of all, I think "annote" (which doesn't seem to be a word: https://www.merriam-webster.com/dictionary/annote) should be changed to "annotation" (https://www.merriam-webster.com/dictionary/annotation).

As for the description, like @adam3smith, I don't think we need to limit intended use to the bibliography. How about "annotation of the item (e.g. for an annotated bibliography)"?

And it's my understanding that this is for annotations like used in e.g. Current Opinion in Biotechnology, right?:

image

(example from https://doi.org/10.1016/j.copbio.2019.12.004)

**Comment by denismaier** [comment]
@rmzelle "annotation of the item (e.g. for an annotated bibliography)" looks good. 

I'll open a new issue concerning `annote` vs `annotation`.

**Comment by denismaier** [comment]
Ok. I have updated the PR to "annotation of the item (e.g. for an annotated bibliography)"

**Comment by bwiernik** [comment]
No, I don't think we should say "for an annotated bibliography".

It's important to distinguish two types of annotations here. First is the long descriptive paragraph for the item ("Recent review on the role…"). The established convention for those sort of long annotations is to store them in `note`. This is the structure used by Chicago (annotated bibliography) and APA (annotated bibliography) purpose because that is the field that Zotero (**Extra**) and Mendeley (**Note**) adopted for storing this sort of user-written abstract. We should follow that established convention and specify that description in an annotated bibliography should go in `note`.

The second type of markup is decorations like the "• of special interest" and "•• of outstanding interest" shown in the example above. Probably the most widely-used example of this is the convention of marking items included in a systematic review or meta-analysis with an asterisk. Probably the biggest use of `annote` "in the wild" are the `apa-meta-analysis.csl` styles distributed by me and as part of the `papaja` R package, which use `annote` for this purpose. So there is at least a fair amount of meta-analaysis data in the wild with that assumption.

I suggest this wording for `annote`:
`short markup, decoration, or annotation to the item (e.g., to indicate items included in a review); for descriptive text (e.g., in an annotated bibliography), use ``note`` instead`

(With these considerations in mind, I actually think `annotation` would be more confusing. My preference is to leave it as `annote` for backwards compatibility or to change it to `decoration`.)

**Comment by bwiernik** [comment]
So, to be clear, for the example above, the item would be entered as:
```
title: Crucial role of high quality biosamples in biomarker development
annote: ••
note: Recent review on the role of biobanks for the development of biomarkers in personalized medicine. The need for quality defined…
```

**Comment by denismaier** [comment]
So, any opinions? @bwiernik's suggestions make sense to me. Are there compelling reasons not to adopt this version?

**Comment by rmzelle** [comment]
Sounds good to me.

**Comment by denismaier** [comment]
Done.
Ok now?

**Comment by bwiernik** [comment]
Good.

**Comment by bdarcus** [comment]
One little thing (sorry about this; I didn't think about impacts on PRs): I changed the file extensions. 

I think you can resolve this issue by simply doing `git merge origin/master` on your branch, and then committing and pushing.

**Comment by bdarcus** [comment]
Also, we should use the review function to request changes and signal approval. It's better to manage multiple requests, because easier to see at a glance status.

**Comment by denismaier** [comment]
Done; everything rst now.
But: why is the first line displayed in bold (github preview?)

**Comment by bdarcus** [comment]
You had a tab on the second line, which I just fixed.

**Comment by denismaier** [comment]
Oh good. I was just about two open a new PR...

**Pull request merged**
