### PR TITLE
Update the Chicago range-collapsing rules

### PR DESCRIPTION
**Pull request by bdarcus**
Chicago changed the algorithm between 15 and 16, so this updates 
accordingly.

Also updates the broken link.

## Notes and Questions

- Which branch do we merge this with? I am assuming master here.
- Do we, as I do here, just make the change, without any accompanying schema change, or do we add a new `chicago-16` option, assuming some styles may expect the old behavior?

### CODE REVIEW

**Comment by bdarcus** [comment]
> We can simplify the table further.

It's dramatically easier for you to propose this as a suggested change, so that I can see the diff, and click commit ;-)

**Comment by bwiernik** [comment]
Can't actually propose suggestions that edit multiple lines or lines you didn't edit in your PR, or I would have. I can make the commit though.

**Comment by rmzelle** [comment]
> Can't actually propose suggestions that edit multiple lines

https://github.blog/changelog/2020-02-26-multi-line-code-suggestions-beta/

**Comment by bwiernik** [comment]
@johnhpercival Could you weigh in on SBL's expected behavior?

**Comment by denismaier** [comment]
Not 100% sure, but the SBL Handbooks describes itself like this: "A second principle is that the handbook should supplement *The Chicago Manual of Style (CMS)*, except in cases where the field very concsciously and authoritatively adopts a different standard." (p.1). I seriously doubt that this here is a case of "concsciously and authoritatively" adopting a different standard. I guess just using the revised guidelines should be ok.

**Comment by denismaier** [comment]
I'm agnostic concerning keeping the old algorithm around. Given that processsors should already have this implemented, keeping it around for a while should do no harm. If it turns out that styles don't use `chicago-15` we can always remove it in a next version.

**Comment by bdarcus** [comment]
If we keep it around, we'd need to amend this PR to have both, I guess.

>

**Comment by bdarcus** [comment]
Also, seems this should go in 1.1, as this involves a processing change?

**Comment by denismaier** [comment]
Or 1.2 in November ;-)

**Comment by johnhpercival** [comment]
> @johnhpercival Could you weigh in on SBL's expected behavior?

I've had a quick look through their journal from the last 5 years, but couldn't find any examples meeting the quite narrow criteria. I did note in the SBL Handbook that they make omitting digits optional: "the last number may be abbreviated by omitting certain repeated digits." This may explain the example given. For an authoritative answer I would suggest emailing them: sblhs2@sbl-site.org (the address given on https://sblhs2.com/)

**Comment by bwiernik** [comment]
Thanks!

**Comment by bwiernik** [comment]
@bdarcus I think we are good to merge this? `master` seems fne--it's just a dropping of a condition by a processor if needed.

**Comment by denismaier** [comment]
@bdarcus @bwiernik What about this now? Shall we merge now, or should it end up in 1.1?

**Comment by bdarcus** [comment]
> @bdarcus @bwiernik What about this now? Shall we merge now, or should it end up in 1.1?

I think my [point above](https://github.com/citation-style-language/documentation/pull/115#issuecomment-667709196) concluding it would need to be 1.1 still stands?

**Comment by denismaier** [comment]
@bdarcus In principle, 1.1 would be a good fit as this here involves some changes to the processor logic. OTOH, these changes are should be rather minimal as @bwiernik says, and, not making this change, may lead to inaccurate results in some (edge) cases. So we might want to consider this as a bug-fix, sort of.

**Comment by bdarcus** [comment]
> @bdarcus In principle, 1.1 would be a good fit as this here involves some changes to the processor logic. OTOH, these changes are should be rather minimal as @bwiernik says, and, not making this change, may lead to inaccurate results in some (edge) cases. So we might want to consider this as a bug-fix, sort of.

My view is if a developer writes code to implement what's in the 1.0 spec, and then we change the spec in such a way they have to change their code, that should not be done in a minor release. That's just bad form.

@cormacrelf - any thoughts on this?

**Comment by cormacrelf** [comment]
It would be better to add "chicago-16" rather than change the meaning of "chicago" and add a -15. That would be 100% backwards compatible and zero problem for a minor release.

**Comment by bwiernik** [comment]
Okay, let’s add Chicago-16 and Chicago-15, deprecate “Chicago”?

**Comment by bwiernik** [comment]
Okay, I've pushed that. This should be good to merge then.

**Pull request merged**
