### PR TITLE
Add section "Types" to list of terms

### PR DESCRIPTION
**Pull request by denismaier**
Companion PR for https://github.com/citation-style-language/schema/pull/257

This adds a new section "Types" to the list of terms.

### CODE REVIEW

**Comment by denismaier** [comment]
> But will also need:
> 
> * `type`
>   
>   * `type` is special term. `<text term="type"/>` renders the term corresponding to the item's `type`

Didn't we agree to add the special logic on 1.1?
This here should only add the terms themselves.

**Comment by bwiernik** [comment]
@bdarcus Good to merge?

**Comment by bdarcus** [comment]
I think something wrong with the commits here. I see one I merged earlier, but no new types.

**Comment by denismaier** [comment]
No, that should be alright.
This only adds this here to the documentation:
```
Types
~~~~~~~~
For each item type listed in Appendix III, there is a corresponding term.
```

**Comment by bdarcus** [comment]
> This only adds this here to the documentation:

What about [this](https://github.com/citation-style-language/documentation/pull/91/files#diff-2ef02f8a5e57337f1e6d71662b58ce6aR202)?

**Comment by bwiernik** [comment]
Don’t worry about it.

**Comment by denismaier** [comment]
> > This only adds this here to the documentation:
> 
> What about [this](https://github.com/citation-style-language/documentation/pull/91/files#diff-2ef02f8a5e57337f1e6d71662b58ce6aR202)?

Don't know. It's only a whitespace issue, right?

**Comment by bdarcus** [comment]
> Don't know. It's only a whitespace issue, right?

It looks like it "adds" content from a previous commit.

**Pull request merged**
