### PR TITLE
Add description for "container" date

### PR DESCRIPTION
**Pull request by njbart**

### CODE REVIEW

**Comment by jayvdb** [comment]
Seems to be reasonable and much needed description, as this one is very confusingly named for a date.
Why no feedback from maintainers?  Seems simple...

**Comment by rmzelle** [comment]
@adam3smith, have you ever come across any tool/style that used the "container" date variable? Does this description look okay?

(also cc'ing @bdarcus for extra cheer)

**Comment by bdarcus** [comment]
I'm just going through these PRs now to try to whittle these down. Sorry about missing this.

So container date; I have to pause for a second to think about a use case.

Maybe a work that's published in a larger collection; say MLKs speeches, where the speech was from one date, and the collection is published on another?

Any reason not to merge this now?

Obviously if we merge, the merge conflict would need to be resolved. I think a `get merge master` will fix it, as it's probably just because I changed the file extension. But this has been sitting here so long, not sure if that's too much to ask.

**Comment by bwiernik** [comment]
I think we should just deprecate `container`. `issued` already is used to mean the publication date of the way that you would retrieve the item, often of the container (e.g., the book for `chapter`, the journal issue for `article-journal`). Something like the speech example I would say the date of the speech would be `event-date`. I really can't see a use case for `container`, and if such a date did exist, it should be called `container-date` or maybe `collection-date`. All of the examples I could come up with were really better described as combinations of `issued` and `event-date`.

**Comment by denismaier** [comment]
Or remove already now. I don't think the variable is really used by styles in  the official repo. There are a couple that have it  in a list with other date variables. @bwiernik  Right? And we could also just change those styles.

**Comment by bwiernik** [comment]
I'm fine with that.

**Comment by bwiernik** [comment]
@bdarcus Your call--remove the `container` variable in 1.0.2 or 1.1? It would be a trivial change to a few styles in the repo to remove it.

**Comment by bdarcus** [comment]
Let's remove it now; it doesn't really make any sense.

**Pull request closed without merging**
