### PR TITLE
Update locale fallback table. Fix #48

### LINKED ISSUE #48: No locale fallback specified for fr and es
I would assume `fr-CL` to fallback to `fr-FR` and `es-CL` to `es-ES`, but these are not listed in the [table in the CSL spec](http://docs.citationstyles.org/en/stable/specification.html#locale-fallback).

### PR DESCRIPTION
**Pull request by customcommander**
Ping @rmzelle, @adam3smith :-)

### CODE REVIEW

**Comment by customcommander** [comment]
👋
@rmzelle @fbennett ?

**Comment by customcommander** [comment]
@rmzelle @adam3smith Morning guys, is this the correct repo or shall I open a PR in another one? ☺️

**Comment by rmzelle** [comment]
@adam3smith, happy with my changes? I figured it would be a little clearer if I added the language/locale descriptions to the locale codes.

**Comment by rmzelle** [comment]
> @rmzelle @adam3smith Morning guys, is this the correct repo or shall I open a PR in another one?

No, this is the right place. We're just very slow.

**Comment by adam3smith** [comment]
Thanks, looks good!

**Comment by rmzelle** [comment]
> Thanks, looks good!

@adam3smith, I set up an organization-wide project, by the way, to track which pull requests should receive a mention in the change log of the next CSL release: https://github.com/orgs/citation-style-language/projects/1. We can pull in zotero-bits issues as we address them.

**Comment by customcommander** [comment]
@rmzelle @adam3smith It doesn't seem that the locales fallback table has been updated/deployed. I'm happy to help but I presume this would require access to some private publishing tools.

The doc as of now:

screen shot 2019-01-11 at 13 58 09

**Comment by rmzelle** [comment]
> It doesn't seem that the locales fallback table has been updated/deployed.

You're looking at the "1.0.1" branch. See https://docs.citationstyles.org/en/master/specification.html#locale-fallback for the updated version. I rather not backport this change to CSL 1.0.1.

**Comment by customcommander** [comment]
Ohh I see. I didn't even notice that! Ok fine by me. Thanks ;)

**Pull request merged**
