### PR TITLE
document how to match numbers against the long ordinals group. fix #58

### LINKED ISSUE #58: Fallback for long-ordinal terms
Hi,

From the doc at http://docs.citationstyles.org/en/1.0.1/specification.html#number

> Long ordinals are defined with the terms “long-ordinal-01” to “long-ordinal-10”, which are used for the numbers 1 through 10. For other numbers “long-ordinal” falls back to “ordinal”.

I have two questions:

1. What is the default match attribute for long-ordinal terms? Is it "whole-number"?
2. Should you always fallback to "short" ordinals or only if the number to ordinalize is bigger than 10?

Thanks!

### PR DESCRIPTION
**Pull request by customcommander**

### CODE REVIEW

**Comment by customcommander** [comment]
@rmzelle 👋

**Comment by customcommander** [comment]
@rmzelle Any feedback? :)

**Comment by rmzelle** [comment]
Sorry I'm letting this sit so long. You're certainly right that we should define the fallback behavior from "long-ordinal" terms to "ordinal" terms, but there are some issue with your current addition:

* the fallback logic you're described isn't quite right ("If no term matches, the number is matched against the "ordinal-00" through "ordinal-09" group and/or the "ordinal-10" through "ordinal-99" group and follows the matching rules of these groups."), as ordinal suffix term use is more complex than that. E.g. some locales only define the "ordinal" term, but you'd still have fallback in this case.
* there is some redundancy for ""long-ordinal-01" through "long-ordinal-10" - a term in this group is used when the number is the same as that of the term" with

  > “long-ordinal” - e.g. “first”, “second”, “third”. Long ordinals are defined with the terms “long-ordinal-01” to “long-ordinal-10”, which are used for the numbers 1 through 10. For other numbers “long-ordinal” falls back to “ordinal”.

  (http://docs.citationstyles.org/en/1.0.1/specification.html#number)
 
* it's not in the right spot in the specification, and it's currently under "Ordinal Suffixes", and "long-ordinal" terms don't define suffixes.

I'll get to this eventually, but it's not mergeable right now. Perhaps we should just expand the current paragraph on term fallback behavior at http://docs.citationstyles.org/en/1.0.1/specification.html#terms, and maybe change

> If a style uses a term in a form that is undefined (even after Locale Fallback), there is fallback to other forms: “verb-short” first falls back to “verb”, “symbol” first falls back to “short”, and “verb” and “short” both fall back to “long”. If no locale or form fallback is available, the term is rendered as an empty string.

to 

> If a style ... back to “long”. In addition, the terms "long-ordinal-1" to "long-ordinal-10" fall back to the set of ordinal suffix terms. If no locale ... an empty string. 

Let me mull it over a bit more.

**Comment by bdarcus** [comment]
Bumping.

Obviously if we merge, the conflict would need to be resolved. I think a `get merge master` will fix it, as it's probably just because I changed the file extension.

**Comment by customcommander** [comment]
@bdarcus And done ;)

**Review by bwiernik — COMMENTED** [review]
I opened a new PR with the simpler description suggested by @rmzelle

**Pull request closed without merging**
